version: '3.8'

services:
  clickhouse1:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-24.4-alpine}'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse1
    container_name: metabase-clickhouse-server-node-1
    ports:
      - '8124:8123'
      - '9000:9000'
      - '9181:9181'
    volumes:
      - './.docker/clickhouse/cluster/server1_config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/cluster/server1_macros.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml'

  clickhouse2:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-24.4-alpine}'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse2
    container_name: metabase-clickhouse-server-node-2
    ports:
      - '8125:8123'
      - '9001:9000'
      - '9182:9181'
    volumes:
      - './.docker/clickhouse/cluster/server2_config.xml:/etc/clickhouse-server/config.xml'
      - './.docker/clickhouse/cluster/server2_macros.xml:/etc/clickhouse-server/config.d/macros.xml'
      - './.docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml'

  # Using Nginx as a cluster entrypoint and a round-robin load balancer for HTTP requests
  nginx:
    image: 'nginx:1.23.1-alpine'
    hostname: nginx
    ports:
      - '8123:8123'
    volumes:
      - './.docker/nginx/local.conf:/etc/nginx/conf.d/local.conf'
    container_name: metabase-nginx

  metabase:
    image: metabase/metabase:v0.49.0-RC1
    container_name: metabase-with-clickhouse-driver-cluster
    environment:
      'MB_HTTP_TIMEOUT': '5000'
      'JAVA_TIMEZONE': 'UTC'
    ports:
      - '3000:3000'
    volumes:
      - '../../../resources/modules/clickhouse.metabase-driver.jar:/plugins/clickhouse.jar'
      - './.docker/clickhouse/single_node_tls/certificates/ca.crt:/certs/ca.crt'
